/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaStylesRouteImport } from './routes/yoga-styles'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ClassScheduleRouteImport } from './routes/class-schedule'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as NlKennisbankRouteImport } from './routes/nl.kennisbank'
import { Route as EnSportbitRouteImport } from './routes/en.sportbit'
import { Route as EnScheduleRouteImport } from './routes/en.schedule'
import { Route as EnPricingRouteImport } from './routes/en.pricing'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnClassesRouteImport } from './routes/en.classes'
import { Route as AdminKennisbankPublicatiesRouteImport } from './routes/admin.kennisbank-publicaties'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as NlKennisbankIndexRouteImport } from './routes/nl.kennisbank.index'
import { Route as NlKennisbankAlleArtikelenRouteImport } from './routes/nl.kennisbank.alle-artikelen'
import { Route as NlKennisbankSlugRouteImport } from './routes/nl.kennisbank.$slug'
import { Route as ApiV1KennisbankSummaryRouteImport } from './routes/api/v1/kennisbank-summary'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as NlKennisbankCategorieIndexRouteImport } from './routes/nl.kennisbank.categorie.index'
import { Route as NlKennisbankPreviewArticleIdRouteImport } from './routes/nl.kennisbank.preview.$articleId'
import { Route as NlKennisbankCategorieSlugRouteImport } from './routes/nl.kennisbank.categorie.$slug'
import { Route as ApiPublicV1KennisbankSummaryRouteImport } from './routes/api/public/v1/kennisbank-summary'

const YogaStylesRoute = YogaStylesRouteImport.update({
  id: '/yoga-styles',
  path: '/yoga-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassScheduleRoute = ClassScheduleRouteImport.update({
  id: '/class-schedule',
  path: '/class-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const NlKennisbankRoute = NlKennisbankRouteImport.update({
  id: '/nl/kennisbank',
  path: '/nl/kennisbank',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSportbitRoute = EnSportbitRouteImport.update({
  id: '/en/sportbit',
  path: '/en/sportbit',
  getParentRoute: () => rootRouteImport,
} as any)
const EnScheduleRoute = EnScheduleRouteImport.update({
  id: '/en/schedule',
  path: '/en/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnClassesRoute = EnClassesRouteImport.update({
  id: '/en/classes',
  path: '/en/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKennisbankPublicatiesRoute =
  AdminKennisbankPublicatiesRouteImport.update({
    id: '/admin/kennisbank-publicaties',
    path: '/admin/kennisbank-publicaties',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const NlKennisbankIndexRoute = NlKennisbankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NlKennisbankRoute,
} as any)
const NlKennisbankAlleArtikelenRoute =
  NlKennisbankAlleArtikelenRouteImport.update({
    id: '/alle-artikelen',
    path: '/alle-artikelen',
    getParentRoute: () => NlKennisbankRoute,
  } as any)
const NlKennisbankSlugRoute = NlKennisbankSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NlKennisbankRoute,
} as any)
const ApiV1KennisbankSummaryRoute = ApiV1KennisbankSummaryRouteImport.update({
  id: '/api/v1/kennisbank-summary',
  path: '/api/v1/kennisbank-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const NlKennisbankCategorieIndexRoute =
  NlKennisbankCategorieIndexRouteImport.update({
    id: '/categorie/',
    path: '/categorie/',
    getParentRoute: () => NlKennisbankRoute,
  } as any)
const NlKennisbankPreviewArticleIdRoute =
  NlKennisbankPreviewArticleIdRouteImport.update({
    id: '/preview/$articleId',
    path: '/preview/$articleId',
    getParentRoute: () => NlKennisbankRoute,
  } as any)
const NlKennisbankCategorieSlugRoute =
  NlKennisbankCategorieSlugRouteImport.update({
    id: '/categorie/$slug',
    path: '/categorie/$slug',
    getParentRoute: () => NlKennisbankRoute,
  } as any)
const ApiPublicV1KennisbankSummaryRoute =
  ApiPublicV1KennisbankSummaryRouteImport.update({
    id: '/api/public/v1/kennisbank-summary',
    path: '/api/public/v1/kennisbank-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/class-schedule': typeof ClassScheduleRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trial': typeof TrialRoute
  '/yoga-styles': typeof YogaStylesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kennisbank-publicaties': typeof AdminKennisbankPublicatiesRoute
  '/en/classes': typeof EnClassesRoute
  '/en/contact': typeof EnContactRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/schedule': typeof EnScheduleRoute
  '/en/sportbit': typeof EnSportbitRoute
  '/nl/kennisbank': typeof NlKennisbankRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/kennisbank-summary': typeof ApiV1KennisbankSummaryRoute
  '/nl/kennisbank/$slug': typeof NlKennisbankSlugRoute
  '/nl/kennisbank/alle-artikelen': typeof NlKennisbankAlleArtikelenRoute
  '/nl/kennisbank/': typeof NlKennisbankIndexRoute
  '/api/public/v1/kennisbank-summary': typeof ApiPublicV1KennisbankSummaryRoute
  '/nl/kennisbank/categorie/$slug': typeof NlKennisbankCategorieSlugRoute
  '/nl/kennisbank/preview/$articleId': typeof NlKennisbankPreviewArticleIdRoute
  '/nl/kennisbank/categorie/': typeof NlKennisbankCategorieIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/class-schedule': typeof ClassScheduleRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trial': typeof TrialRoute
  '/yoga-styles': typeof YogaStylesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kennisbank-publicaties': typeof AdminKennisbankPublicatiesRoute
  '/en/classes': typeof EnClassesRoute
  '/en/contact': typeof EnContactRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/schedule': typeof EnScheduleRoute
  '/en/sportbit': typeof EnSportbitRoute
  '/en': typeof EnIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/kennisbank-summary': typeof ApiV1KennisbankSummaryRoute
  '/nl/kennisbank/$slug': typeof NlKennisbankSlugRoute
  '/nl/kennisbank/alle-artikelen': typeof NlKennisbankAlleArtikelenRoute
  '/nl/kennisbank': typeof NlKennisbankIndexRoute
  '/api/public/v1/kennisbank-summary': typeof ApiPublicV1KennisbankSummaryRoute
  '/nl/kennisbank/categorie/$slug': typeof NlKennisbankCategorieSlugRoute
  '/nl/kennisbank/preview/$articleId': typeof NlKennisbankPreviewArticleIdRoute
  '/nl/kennisbank/categorie': typeof NlKennisbankCategorieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/class-schedule': typeof ClassScheduleRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trial': typeof TrialRoute
  '/yoga-styles': typeof YogaStylesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kennisbank-publicaties': typeof AdminKennisbankPublicatiesRoute
  '/en/classes': typeof EnClassesRoute
  '/en/contact': typeof EnContactRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/schedule': typeof EnScheduleRoute
  '/en/sportbit': typeof EnSportbitRoute
  '/nl/kennisbank': typeof NlKennisbankRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/kennisbank-summary': typeof ApiV1KennisbankSummaryRoute
  '/nl/kennisbank/$slug': typeof NlKennisbankSlugRoute
  '/nl/kennisbank/alle-artikelen': typeof NlKennisbankAlleArtikelenRoute
  '/nl/kennisbank/': typeof NlKennisbankIndexRoute
  '/api/public/v1/kennisbank-summary': typeof ApiPublicV1KennisbankSummaryRoute
  '/nl/kennisbank/categorie/$slug': typeof NlKennisbankCategorieSlugRoute
  '/nl/kennisbank/preview/$articleId': typeof NlKennisbankPreviewArticleIdRoute
  '/nl/kennisbank/categorie/': typeof NlKennisbankCategorieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/class-schedule'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/trial'
    | '/yoga-styles'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kennisbank-publicaties'
    | '/en/classes'
    | '/en/contact'
    | '/en/pricing'
    | '/en/schedule'
    | '/en/sportbit'
    | '/nl/kennisbank'
    | '/en/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/kennisbank-summary'
    | '/nl/kennisbank/$slug'
    | '/nl/kennisbank/alle-artikelen'
    | '/nl/kennisbank/'
    | '/api/public/v1/kennisbank-summary'
    | '/nl/kennisbank/categorie/$slug'
    | '/nl/kennisbank/preview/$articleId'
    | '/nl/kennisbank/categorie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/class-schedule'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/trial'
    | '/yoga-styles'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kennisbank-publicaties'
    | '/en/classes'
    | '/en/contact'
    | '/en/pricing'
    | '/en/schedule'
    | '/en/sportbit'
    | '/en'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/kennisbank-summary'
    | '/nl/kennisbank/$slug'
    | '/nl/kennisbank/alle-artikelen'
    | '/nl/kennisbank'
    | '/api/public/v1/kennisbank-summary'
    | '/nl/kennisbank/categorie/$slug'
    | '/nl/kennisbank/preview/$articleId'
    | '/nl/kennisbank/categorie'
  id:
    | '__root__'
    | '/auth'
    | '/class-schedule'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/trial'
    | '/yoga-styles'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kennisbank-publicaties'
    | '/en/classes'
    | '/en/contact'
    | '/en/pricing'
    | '/en/schedule'
    | '/en/sportbit'
    | '/nl/kennisbank'
    | '/en/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/kennisbank-summary'
    | '/nl/kennisbank/$slug'
    | '/nl/kennisbank/alle-artikelen'
    | '/nl/kennisbank/'
    | '/api/public/v1/kennisbank-summary'
    | '/nl/kennisbank/categorie/$slug'
    | '/nl/kennisbank/preview/$articleId'
    | '/nl/kennisbank/categorie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  ClassScheduleRoute: typeof ClassScheduleRoute
  McpRoute: typeof McpRoute
  PricesRoute: typeof PricesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrialRoute: typeof TrialRoute
  YogaStylesRoute: typeof YogaStylesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminKennisbankPublicatiesRoute: typeof AdminKennisbankPublicatiesRoute
  EnClassesRoute: typeof EnClassesRoute
  EnContactRoute: typeof EnContactRoute
  EnPricingRoute: typeof EnPricingRoute
  EnScheduleRoute: typeof EnScheduleRoute
  EnSportbitRoute: typeof EnSportbitRoute
  NlKennisbankRoute: typeof NlKennisbankRouteWithChildren
  EnIndexRoute: typeof EnIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiV1KennisbankSummaryRoute: typeof ApiV1KennisbankSummaryRoute
  ApiPublicV1KennisbankSummaryRoute: typeof ApiPublicV1KennisbankSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga-styles': {
      id: '/yoga-styles'
      path: '/yoga-styles'
      fullPath: '/yoga-styles'
      preLoaderRoute: typeof YogaStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-schedule': {
      id: '/class-schedule'
      path: '/class-schedule'
      fullPath: '/class-schedule'
      preLoaderRoute: typeof ClassScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl/kennisbank': {
      id: '/nl/kennisbank'
      path: '/nl/kennisbank'
      fullPath: '/nl/kennisbank'
      preLoaderRoute: typeof NlKennisbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sportbit': {
      id: '/en/sportbit'
      path: '/en/sportbit'
      fullPath: '/en/sportbit'
      preLoaderRoute: typeof EnSportbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/schedule': {
      id: '/en/schedule'
      path: '/en/schedule'
      fullPath: '/en/schedule'
      preLoaderRoute: typeof EnScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/classes': {
      id: '/en/classes'
      path: '/en/classes'
      fullPath: '/en/classes'
      preLoaderRoute: typeof EnClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kennisbank-publicaties': {
      id: '/admin/kennisbank-publicaties'
      path: '/admin/kennisbank-publicaties'
      fullPath: '/admin/kennisbank-publicaties'
      preLoaderRoute: typeof AdminKennisbankPublicatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl/kennisbank/': {
      id: '/nl/kennisbank/'
      path: '/'
      fullPath: '/nl/kennisbank/'
      preLoaderRoute: typeof NlKennisbankIndexRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/nl/kennisbank/alle-artikelen': {
      id: '/nl/kennisbank/alle-artikelen'
      path: '/alle-artikelen'
      fullPath: '/nl/kennisbank/alle-artikelen'
      preLoaderRoute: typeof NlKennisbankAlleArtikelenRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/nl/kennisbank/$slug': {
      id: '/nl/kennisbank/$slug'
      path: '/$slug'
      fullPath: '/nl/kennisbank/$slug'
      preLoaderRoute: typeof NlKennisbankSlugRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/api/v1/kennisbank-summary': {
      id: '/api/v1/kennisbank-summary'
      path: '/api/v1/kennisbank-summary'
      fullPath: '/api/v1/kennisbank-summary'
      preLoaderRoute: typeof ApiV1KennisbankSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl/kennisbank/categorie/': {
      id: '/nl/kennisbank/categorie/'
      path: '/categorie'
      fullPath: '/nl/kennisbank/categorie/'
      preLoaderRoute: typeof NlKennisbankCategorieIndexRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/nl/kennisbank/preview/$articleId': {
      id: '/nl/kennisbank/preview/$articleId'
      path: '/preview/$articleId'
      fullPath: '/nl/kennisbank/preview/$articleId'
      preLoaderRoute: typeof NlKennisbankPreviewArticleIdRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/nl/kennisbank/categorie/$slug': {
      id: '/nl/kennisbank/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/nl/kennisbank/categorie/$slug'
      preLoaderRoute: typeof NlKennisbankCategorieSlugRouteImport
      parentRoute: typeof NlKennisbankRoute
    }
    '/api/public/v1/kennisbank-summary': {
      id: '/api/public/v1/kennisbank-summary'
      path: '/api/public/v1/kennisbank-summary'
      fullPath: '/api/public/v1/kennisbank-summary'
      preLoaderRoute: typeof ApiPublicV1KennisbankSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NlKennisbankRouteChildren {
  NlKennisbankSlugRoute: typeof NlKennisbankSlugRoute
  NlKennisbankAlleArtikelenRoute: typeof NlKennisbankAlleArtikelenRoute
  NlKennisbankIndexRoute: typeof NlKennisbankIndexRoute
  NlKennisbankCategorieSlugRoute: typeof NlKennisbankCategorieSlugRoute
  NlKennisbankPreviewArticleIdRoute: typeof NlKennisbankPreviewArticleIdRoute
  NlKennisbankCategorieIndexRoute: typeof NlKennisbankCategorieIndexRoute
}

const NlKennisbankRouteChildren: NlKennisbankRouteChildren = {
  NlKennisbankSlugRoute: NlKennisbankSlugRoute,
  NlKennisbankAlleArtikelenRoute: NlKennisbankAlleArtikelenRoute,
  NlKennisbankIndexRoute: NlKennisbankIndexRoute,
  NlKennisbankCategorieSlugRoute: NlKennisbankCategorieSlugRoute,
  NlKennisbankPreviewArticleIdRoute: NlKennisbankPreviewArticleIdRoute,
  NlKennisbankCategorieIndexRoute: NlKennisbankCategorieIndexRoute,
}

const NlKennisbankRouteWithChildren = NlKennisbankRoute._addFileChildren(
  NlKennisbankRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  ClassScheduleRoute: ClassScheduleRoute,
  McpRoute: McpRoute,
  PricesRoute: PricesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrialRoute: TrialRoute,
  YogaStylesRoute: YogaStylesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminKennisbankPublicatiesRoute: AdminKennisbankPublicatiesRoute,
  EnClassesRoute: EnClassesRoute,
  EnContactRoute: EnContactRoute,
  EnPricingRoute: EnPricingRoute,
  EnScheduleRoute: EnScheduleRoute,
  EnSportbitRoute: EnSportbitRoute,
  NlKennisbankRoute: NlKennisbankRouteWithChildren,
  EnIndexRoute: EnIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiV1KennisbankSummaryRoute: ApiV1KennisbankSummaryRoute,
  ApiPublicV1KennisbankSummaryRoute: ApiPublicV1KennisbankSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
